### ISSUE TITLE
Tracking issue: Lunarity's parser

### ISSUE THREAD

**Issue by abs0luty** [abs0luty/taurine-project#1]
# Description

This issue tracks progress of writing Lunarity's parser.

# Progress

- [x] Scan ASCII identifiers
- [x] Scan identifiers containing non ASCII symbols (Unicode XID)
  - [x] Add Unicode XID support to Arty
- [x] Scan punctuation tokens
- [x] Minimally scan string tokens
- [ ] Escape sequences in strings
  - [x] Partially implement `vec` to be able to easily create dynamic strings
  - [x] Standard ASCII escape sequences in strings
  - [ ] Unicode escape sequences in strings
- [ ] Scan numbers
- [x] Write down Lunarity's context-free grammar
- [ ] Expression parser
- [ ] Statement parser
- [ ] Chunk parser
